# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
#' @rdname Atoms
#' @noRd
.LAMMPSParser <- function(files, selection = as.integer( c(-1)), first = as.integer( c(1)), last = as.integer( c(-1)), stride = as.integer( c(1))) {
    .Call('_Atoms_LAMMPSParser', PACKAGE = 'Atoms', files, selection, first, last, stride)
}

#' @export
#' @rdname Atoms
#' @noRd
.MOL2Parser <- function(files, selection = as.integer( c(-1)), first = as.integer( c(1)), last = as.integer( c(-1)), stride = as.integer( c(1))) {
    .Call('_Atoms_MOL2Parser', PACKAGE = 'Atoms', files, selection, first, last, stride)
}

#' @export
#' @rdname Atoms
#' @noRd
.PDBParser <- function(files, selection = as.integer( c(-1)), first = as.integer( c(1)), last = as.integer( c(-1)), stride = as.integer( c(1))) {
    .Call('_Atoms_PDBParser', PACKAGE = 'Atoms', files, selection, first, last, stride)
}

#' @export
#' @rdname writeAtoms
#' @noRd
.PDBWriter <- function(x, file) {
    invisible(.Call('_Atoms_PDBWriter', PACKAGE = 'Atoms', x, file))
}

#' @export
#' @rdname Atoms
#' @noRd
.RESParser <- function(files, selection = as.integer( c(-1)), first = as.integer( c(1)), last = as.integer( c(-1)), stride = as.integer( c(1))) {
    .Call('_Atoms_RESParser', PACKAGE = 'Atoms', files, selection, first, last, stride)
}

#' @export
#' @rdname writeAtoms
#' @noRd
.RESWriter <- function(x, file) {
    invisible(.Call('_Atoms_RESWriter', PACKAGE = 'Atoms', x, file))
}

#' @export
#' @rdname Atoms
#' @noRd
.XYZParser <- function(files, selection = as.integer( c(-1)), first = as.integer( c(1)), last = as.integer( c(-1)), stride = as.integer( c(1))) {
    .Call('_Atoms_XYZParser', PACKAGE = 'Atoms', files, selection, first, last, stride)
}

#' @export
#' @rdname writeAtoms
#' @noRd
.XYZWriter <- function(x, file) {
    invisible(.Call('_Atoms_XYZWriter', PACKAGE = 'Atoms', x, file))
}

#' @rdname com
#' @export
.comAtoms <- function(x, mass, factor) {
    .Call('_Atoms_comAtoms', PACKAGE = 'Atoms', x, mass, factor)
}

#' @rdname freeVolume
#' @export
freeVolume.Atoms <- function(x, radius = NULL) {
    .Call('_Atoms_freeVolumeAtoms', PACKAGE = 'Atoms', x, radius)
}

#' @rdname freeVolume
#' @export
freeVolume2.Atoms <- function(x, radius = NULL) {
    .Call('_Atoms_freeVolume2Atoms', PACKAGE = 'Atoms', x, radius)
}

#' @rdname guessTopology
#' @export
guessAngles.Atoms <- function(x) {
    .Call('_Atoms_guessAnglesAtoms', PACKAGE = 'Atoms', x)
}

#' @param radius a numeric vector. Atomic radii used to defined bonded atoms.
#' @param safety a numeric value used to extend the atomic radii.
#' @param usePBC a logical value. Whether to use periodic boundary conditions to compute inter-atomic distances.
#' @rdname guessTopology
#' @export
guessBonds.Atoms <- function(x, radius = NULL, safety = 1.2, usePBC = TRUE) {
    .Call('_Atoms_guessBondsAtoms', PACKAGE = 'Atoms', x, radius, safety, usePBC)
}

#' @rdname guessTopology
#' @export
guessDihedrals.Atoms <- function(x) {
    .Call('_Atoms_guessDihedralsAtoms', PACKAGE = 'Atoms', x)
}

#' @rdname guessTopology
#' @export
guessImpropers.Atoms <- function(x) {
    .Call('_Atoms_guessImpropersAtoms', PACKAGE = 'Atoms', x)
}

#' @rdname join
#' @export
.joinAtoms <- function(x, multi) {
    invisible(.Call('_Atoms_joinAtoms', PACKAGE = 'Atoms', x, multi))
}

#' @rdname measure
#' @noRd
#' @export
.measureBonds <- function(x, atm1, atm2) {
    .Call('_Atoms_measureBonds', PACKAGE = 'Atoms', x, atm1, atm2)
}

#' @rdname measure
#' @noRd
#' @export
.measureAngles <- function(x, atm1, atm2, atm3) {
    .Call('_Atoms_measureAngles', PACKAGE = 'Atoms', x, atm1, atm2, atm3)
}

#' @rdname measure
#' @noRd
#' @export
.measureDihedrals <- function(x, atm1, atm2, atm3, atm4) {
    .Call('_Atoms_measureDihedrals', PACKAGE = 'Atoms', x, atm1, atm2, atm3, atm4)
}

#' @rdname planNormals
#' @export
.planNormalsAtoms <- function(x, atm1, atm2, atm3) {
    .Call('_Atoms_planNormalsAtoms', PACKAGE = 'Atoms', x, atm1, atm2, atm3)
}

#' @rdname rdf
#' @export
.rdfAtoms <- function(x, sel1, sel2, resnumb, cutoff, interval, type) {
    .Call('_Atoms_rdfAtoms', PACKAGE = 'Atoms', x, sel1, sel2, resnumb, cutoff, interval, type)
}

#' @rdname rmsd
#' @noRd
#' @export
.rmsdAtoms <- function(x, y, usePBC) {
    .Call('_Atoms_rmsdAtoms', PACKAGE = 'Atoms', x, y, usePBC)
}

#' @rdname vectOrientation
#' @noRd
#' @export
.vectOrientation <- function(x, V1) {
    .Call('_Atoms_vectOrientation', PACKAGE = 'Atoms', x, V1)
}

#' @rdname vectOrientation
#' @noRd
#' @export
.vectOrientationAxis <- function(x, V1, V2) {
    .Call('_Atoms_vectOrientationAxis', PACKAGE = 'Atoms', x, V1, V2)
}

#' @rdname vectOrientation
#' @noRd
#' @export
.vectOrientationPairwise <- function(x, V1, V2) {
    .Call('_Atoms_vectOrientationPairwise', PACKAGE = 'Atoms', x, V1, V2)
}

#' @rdname vectOrientation
#' @noRd
#' @export
.vectOrientationNotPairwise <- function(x, V1, V2) {
    .Call('_Atoms_vectOrientationNotPairwise', PACKAGE = 'Atoms', x, V1, V2)
}

#' @rdname wrap
#' @export
.wrapAtoms <- function(x, resnumb, multi) {
    invisible(.Call('_Atoms_wrapAtoms', PACKAGE = 'Atoms', x, resnumb, multi))
}

